global_frame: odom
rolling_window: true
track_unknown_space: false
width: 75 #150
height: 75 #150
resolution: 0.1


plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
