global_frame: odom
rolling_window: true
width: 25 #100
height: 25 #100
resolution: 0.1

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  # - {name: obstacles_pc2,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
