transform_tolerance: 0.1
min_height: 0.5
max_height: 2
angle_min: -2.35619449019
angle_max: 2.35619449019
angle_increment: 0.01
scan_time: 0.1
range_min: 0.1
range_max: 50.0
target_frame: laser
use_inf: true
concurrency_level: 0
